### ISSUE TITLE
Create file with all refs for merge

### ISSUE THREAD

**Issue by ArnaudGastinel** [juliawildmoka/TestQA#39]
Magic create branches
http://192.168.84.197:8080/job/DevProcessAutomationHook/713/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-39 created for repositories: A,B,C,D,TestQA

**Comment by ArnaudGastinel** [comment]
Magic create pull requests

http://192.168.84.197:8080/job/DevProcessAutomationHook/720/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-39 for repositories: D

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request already exist on another repository, pull request created on branch QA-39 for repository: A

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request is not mergeable on repo {u'issues_url': u'https://api.github.com/repos/juliawildmoka/A/issues{/number}', u'deployments_url': u'https://api.github.com/repos/juliawildmoka/A/deployments', u'has_wiki': True, u'forks_url': u'https://api.github.com/repos/juliawildmoka/A/forks', u'mirror_url': None, u'subscription_url': u'https://api.github.com/repos/juliawildmoka/A/subscription', u'merges_url': u'https://api.github.com/repos/juliawildmoka/A/merges', u'collaborators_url': u'https://api.github.com/repos/juliawildmoka/A/collaborators{/collaborator}', u'updated_at': u'2016-02-05T16:55:44Z', u'private': False, u'pulls_url': u'https://api.github.com/repos/juliawildmoka/A/pulls{/number}', u'issue_comment_url': u'https://api.github.com/repos/juliawildmoka/A/issues/comments{/number}', u'full_name': u'juliawildmoka/A', u'owner': {u'following_url': u'https://api.github.com/users/juliawildmoka/following{/other_user}', u'gists_url': u'https://api.github.com/users/juliawildmoka/gists{/gist_id}', u'organizations_url': u'https://api.github.com/users/juliawildmoka/orgs', u'url': u'https://api.github.com/users/juliawildmoka', u'events_url': u'https://api.github.com/users/juliawildmoka/events{/privacy}', u'html_url': u'https://github.com/juliawildmoka', u'subscriptions_url': u'https://api.github.com/users/juliawildmoka/subscriptions', u'avatar_url': u'https://avatars.githubusercontent.com/u/16668322?v=3', u'repos_url': u'https://api.github.com/users/juliawildmoka/repos', u'received_events_url': u'https://api.github.com/users/juliawildmoka/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/juliawildmoka/starred{/owner}{/repo}', u'site_admin': False, u'login': u'juliawildmoka', u'type': u'User', u'id': 16668322, u'followers_url': u'https://api.github.com/users/juliawildmoka/followers'}, u'statuses_url': u'https://api.github.com/repos/juliawildmoka/A/statuses/{sha}', u'id': 51160309, u'keys_url': u'https://api.github.com/repos/juliawildmoka/A/keys{/key_id}', u'size': 10, u'tags_url': u'https://api.github.com/repos/juliawildmoka/A/tags', u'issue_events_url': u'https://api.github.com/repos/juliawildmoka/A/issues/events{/number}', u'contributors_url': u'https://api.github.com/repos/juliawildmoka/A/contributors', u'downloads_url': u'https://api.github.com/repos/juliawildmoka/A/downloads', u'has_downloads': True, u'assignees_url': u'https://api.github.com/repos/juliawildmoka/A/assignees{/user}', u'contents_url': u'https://api.github.com/repos/juliawildmoka/A/contents/{+path}', u'has_pages': False, u'git_refs_url': u'https://api.github.com/repos/juliawildmoka/A/git/refs{/sha}', u'clone_url': u'https://github.com/juliawildmoka/A.git', u'watchers_count': 0, u'git_tags_url': u'https://api.github.com/repos/juliawildmoka/A/git/tags{/sha}', u'milestones_url': u'https://api.github.com/repos/juliawildmoka/A/milestones{/number}', u'stargazers_count': 0, u'permissions': {u'admin': False, u'push': True, u'pull': True}, u'homepage': None, u'branches_url': u'https://api.github.com/repos/juliawildmoka/A/branches{/branch}', u'fork': False, u'commits_url': u'https://api.github.com/repos/juliawildmoka/A/commits{/sha}', u'releases_url': u'https://api.github.com/repos/juliawildmoka/A/releases{/id}', u'description': u'A', u'archive_url': u'https://api.github.com/repos/juliawildmoka/A/{archive_format}{/ref}', u'labels_url': u'https://api.github.com/repos/juliawildmoka/A/labels{/name}', u'events_url': u'https://api.github.com/repos/juliawildmoka/A/events', u'comments_url': u'https://api.github.com/repos/juliawildmoka/A/comments{/number}', u'html_url': u'https://github.com/juliawildmoka/A', u'forks': 0, u'compare_url': u'https://api.github.com/repos/juliawildmoka/A/compare/{base}...{head}', u'trees_url': u'https://api.github.com/repos/juliawildmoka/A/git/trees{/sha}', u'git_url': u'git://github.com/juliawildmoka/A.git', u'svn_url': u'https://github.com/juliawildmoka/A', u'notifications_url': u'https://api.github.com/repos/juliawildmoka/A/notifications{?since,all,participating}', u'has_issues': True, u'ssh_url': u'git@github.com:juliawildmoka/A.git', u'blobs_url': u'https://api.github.com/repos/juliawildmoka/A/git/blobs{/sha}', u'languages_url': u'https://api.github.com/repos/juliawildmoka/A/languages', u'hooks_url': u'https://api.github.com/repos/juliawildmoka/A/hooks', u'open_issues_count': 1, u'watchers': 0, u'name': u'A', u'language': None, u'url': u'https://api.github.com/repos/juliawildmoka/A', u'created_at': u'2016-02-05T16:55:44Z', u'pushed_at': u'2016-02-15T09:18:37Z', u'forks_count': 0, u'default_branch': u'master', u'teams_url': u'https://api.github.com/repos/juliawildmoka/A/teams', u'open_issues': 1, u'git_commits_url': u'https://api.github.com/repos/juliawildmoka/A/git/commits{/sha}', u'subscribers_url': u'https://api.github.com/repos/juliawildmoka/A/subscribers', u'stargazers_url': u'https://api.github.com/repos/juliawildmoka/A/stargazers'} cannot continue.

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'AUTO Pull request created for issue #QA-39' on A is not mergeable and so not buildable

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request is not mergeable on repo {u'issues_url': u'https://api.github.com/repos/juliawildmoka/A/issues{/number}', u'deployments_url': u'https://api.github.com/repos/juliawildmoka/A/deployments', u'has_wiki': True, u'forks_url': u'https://api.github.com/repos/juliawildmoka/A/forks', u'mirror_url': None, u'subscription_url': u'https://api.github.com/repos/juliawildmoka/A/subscription', u'merges_url': u'https://api.github.com/repos/juliawildmoka/A/merges', u'collaborators_url': u'https://api.github.com/repos/juliawildmoka/A/collaborators{/collaborator}', u'updated_at': u'2016-02-05T16:55:44Z', u'private': False, u'pulls_url': u'https://api.github.com/repos/juliawildmoka/A/pulls{/number}', u'issue_comment_url': u'https://api.github.com/repos/juliawildmoka/A/issues/comments{/number}', u'full_name': u'juliawildmoka/A', u'owner': {u'following_url': u'https://api.github.com/users/juliawildmoka/following{/other_user}', u'gists_url': u'https://api.github.com/users/juliawildmoka/gists{/gist_id}', u'organizations_url': u'https://api.github.com/users/juliawildmoka/orgs', u'url': u'https://api.github.com/users/juliawildmoka', u'events_url': u'https://api.github.com/users/juliawildmoka/events{/privacy}', u'html_url': u'https://github.com/juliawildmoka', u'subscriptions_url': u'https://api.github.com/users/juliawildmoka/subscriptions', u'avatar_url': u'https://avatars.githubusercontent.com/u/16668322?v=3', u'repos_url': u'https://api.github.com/users/juliawildmoka/repos', u'received_events_url': u'https://api.github.com/users/juliawildmoka/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/juliawildmoka/starred{/owner}{/repo}', u'site_admin': False, u'login': u'juliawildmoka', u'type': u'User', u'id': 16668322, u'followers_url': u'https://api.github.com/users/juliawildmoka/followers'}, u'statuses_url': u'https://api.github.com/repos/juliawildmoka/A/statuses/{sha}', u'id': 51160309, u'keys_url': u'https://api.github.com/repos/juliawildmoka/A/keys{/key_id}', u'size': 10, u'tags_url': u'https://api.github.com/repos/juliawildmoka/A/tags', u'issue_events_url': u'https://api.github.com/repos/juliawildmoka/A/issues/events{/number}', u'contributors_url': u'https://api.github.com/repos/juliawildmoka/A/contributors', u'downloads_url': u'https://api.github.com/repos/juliawildmoka/A/downloads', u'has_downloads': True, u'assignees_url': u'https://api.github.com/repos/juliawildmoka/A/assignees{/user}', u'contents_url': u'https://api.github.com/repos/juliawildmoka/A/contents/{+path}', u'has_pages': False, u'git_refs_url': u'https://api.github.com/repos/juliawildmoka/A/git/refs{/sha}', u'clone_url': u'https://github.com/juliawildmoka/A.git', u'watchers_count': 0, u'git_tags_url': u'https://api.github.com/repos/juliawildmoka/A/git/tags{/sha}', u'milestones_url': u'https://api.github.com/repos/juliawildmoka/A/milestones{/number}', u'stargazers_count': 0, u'permissions': {u'admin': False, u'push': True, u'pull': True}, u'homepage': None, u'branches_url': u'https://api.github.com/repos/juliawildmoka/A/branches{/branch}', u'fork': False, u'commits_url': u'https://api.github.com/repos/juliawildmoka/A/commits{/sha}', u'releases_url': u'https://api.github.com/repos/juliawildmoka/A/releases{/id}', u'description': u'A', u'archive_url': u'https://api.github.com/repos/juliawildmoka/A/{archive_format}{/ref}', u'labels_url': u'https://api.github.com/repos/juliawildmoka/A/labels{/name}', u'events_url': u'https://api.github.com/repos/juliawildmoka/A/events', u'comments_url': u'https://api.github.com/repos/juliawildmoka/A/comments{/number}', u'html_url': u'https://github.com/juliawildmoka/A', u'forks': 0, u'compare_url': u'https://api.github.com/repos/juliawildmoka/A/compare/{base}...{head}', u'trees_url': u'https://api.github.com/repos/juliawildmoka/A/git/trees{/sha}', u'git_url': u'git://github.com/juliawildmoka/A.git', u'svn_url': u'https://github.com/juliawildmoka/A', u'notifications_url': u'https://api.github.com/repos/juliawildmoka/A/notifications{?since,all,participating}', u'has_issues': True, u'ssh_url': u'git@github.com:juliawildmoka/A.git', u'blobs_url': u'https://api.github.com/repos/juliawildmoka/A/git/blobs{/sha}', u'languages_url': u'https://api.github.com/repos/juliawildmoka/A/languages', u'hooks_url': u'https://api.github.com/repos/juliawildmoka/A/hooks', u'open_issues_count': 1, u'watchers': 0, u'name': u'A', u'language': None, u'url': u'https://api.github.com/repos/juliawildmoka/A', u'created_at': u'2016-02-05T16:55:44Z', u'pushed_at': u'2016-02-15T09:18:37Z', u'forks_count': 0, u'default_branch': u'master', u'teams_url': u'https://api.github.com/repos/juliawildmoka/A/teams', u'open_issues': 1, u'git_commits_url': u'https://api.github.com/repos/juliawildmoka/A/git/commits{/sha}', u'subscribers_url': u'https://api.github.com/repos/juliawildmoka/A/subscribers', u'stargazers_url': u'https://api.github.com/repos/juliawildmoka/A/stargazers'} cannot continue.

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request is not mergeable on repo A cannot continue.

**Comment by ArnaudGastinel** [comment]
Magic rebuild

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'AUTO Pull request created for issue #QA-39' on A is not mergeable and so not buildable

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by ArnaudGastinel** [comment]
MAGIC rebuild

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by ArnaudGastinel** [comment]
MAGIC REBUILD

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by ArnaudGastinel** [comment]
Magic rebuild

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by ArnaudGastinel** [comment]
Magic rebuild

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by ArnaudGastinel** [comment]
MAGIC REBUILD

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by ArnaudGastinel** [comment]
MERGE REBUILD

**Comment by ArnaudGastinel** [comment]
MAGIC REBUILD

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by ArnaudGastinel** [comment]
MAGIC REBUILD

**Comment by ArnaudGastinel** [comment]
MAGIC rebuild
http://192.168.84.197:8080/job/DevProcessAutomationHook/769/

**Comment by ArnaudGastinel** [comment]
MAGIC REBUILD
http://192.168.84.197:8080/job/DevProcessAutomationHook/770/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by ArnaudGastinel** [comment]
MAGIC REBUILD
http://192.168.84.197:8080/job/DevProcessAutomationHook/779/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by ArnaudGastinel** [comment]
MAGIC REbuild
http://192.168.84.197:8080/job/DevProcessAutomationHook/782/

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by ArnaudGastinel** [comment]
MAGIC REbuild
http://192.168.84.197:8080/job/DevProcessAutomationHook/786/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by ArnaudGastinel** [comment]
MAGIC REBUILD
http://192.168.84.197:8080/job/DevProcessAutomationHook/789/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by ArnaudGastinel** [comment]
MAGIC REBUILD
http://192.168.84.197:8080/job/DevProcessAutomationHook/792/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-39 on repositories A,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC REBUILD
Master has changed from issue 42
http://192.168.84.197:8080/job/DevProcessAutomationHook/837/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'AUTO Pull request created for issue #QA-39' on D is not mergeable and so not buildable
